# tomcat port 설정
server:
  port: 8888

---
# jsp, jstl 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

---
# mybatis, mariadb 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/bootmvc?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hubizict12#    

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

---
#logback 설정
logging:
  level:    
    root: debug
    org:
      springframework: info
      apache:
        tomcat: info          
        catalina: info
        coyote: info
        jasper: info
    jdbc:
      sqlonly: debug
      resultsettable: debug
    com:
      zaxxer: info    
     
---
logging:
  level:
    org:
      apache:
        tomcat:
          util:
            scan:
              StandardJarScanner: error        