# tomcat port 설정
server:
  port: 8888

---
# jsp, jstl 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

---
# mybatis, mariadb 설정
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/bootmvc?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hubizict12#    

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

---
#logback 설정
logging:
  level:    
    root: debug
    org:
      springframework: info
      apache:
        tomcat: info          
        catalina: info
        coyote: info
        jasper: info    
    jdbc:
      sqlonly: warn
      sqltiming: debug
      resultsettable: debug
      audit: warn
      connection: warn
      resultset: warn
    com:
      zaxxer: info    
     
---
logging:
  level:
    org:
      apache:
        tomcat:
          util:
            scan:
              StandardJarScanner: error        